image: java:8-jdk

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
    - ./gradlew build
    - ./gradlew copyJarToBin
  artifacts:
    paths:
      - build/libs/FurnitureLib.jar
    expire_in: 1 week
  only:
    - master

after_script:
  - echo "End CI"