image: gradle:jdk17

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
    - gradle --build-cache assemble
    - gradle copyJarToBin
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/ProtectionLib.jar
    expire_in: 1 week
  only:
    - master

after_script:
  - echo "End CI"